### ISSUE TITLE
midi clock out broken

### ISSUE THREAD

**Issue by y1ds** [ahlstromcj/sequencer64#123]
somewhere between commit f21081ecfccccbf3aa2afc02dcac02f46ea70519 and 5d8d297406646ce1fd19cc8f739afe789de34972 midi clock output seems to have broken.
When enabled for a port, i get position and continue midi messages, no midi clock messages.
at commit f21081ecfccccbf3aa2afc02dcac02f46ea70519 it wroks as expected, it sends out midi clock messages and I can my external equipment.

**Comment by ahlstromcj** [comment]
I assume it is in the native JACK mode. If so, I have a suspect. Might not
get to it tonight due to some wild grandsons! Thanks for the report!

**Comment by ahlstromcj** [comment]
I found an error in JACK Transport, but it basically kept the progress bar from moving.  That will probably result in 0.94.1 real soon if I can't figure out your issue.  I'm not sure how your getting position and continue messages, because they and the clock messages seem to output F0 only, instead of their proper numbers (e.g. F8 for clock).  I'm feeding the correct values to the JACK write function, but they arrive at Yoshimi as F0, and QMidiArp calls them "unknown event".  Very puzzling!  I've found a few differences between the two commits, but nothing other than the JACK Transport issues can I see, so far.

**Comment by ahlstromcj** [comment]
I think I may have fixed this one with the fix noted above.  I ran the jack_midi_clock program (a project on github) and the jack_trans2midi program (sourceforge).  The same issues with Yoshimi and QMidiArp as noted above occurred with these programs as well.  Puzzled!

If you get a chance, please re-test and let me know what you see.  Thanks!  You can use master 0.94.1 or tempo_track 0.94.2 to test.

**Comment by y1ds** [comment]
seems resolved, havent tested it with my external equipment, but I see midi clock messages comming out of seq64 again.
thanks :)

**Comment by ahlstromcj** [comment]
Cool.
