### ISSUE TITLE
Windows build status update question

### ISSUE THREAD

**Issue by Gimmeapill** [ahlstromcj/sequencer64#140]
Hello Chris,

I've ignited some interest among users of the legacy Seq24 on Windows (on another forum), yet I was unable to locate any Windows binary of Sequencer64.
The todo mentions that the Windows branch misses an installer and build scripts, is it still in the plans?

BR,

LX

**Comment by ahlstromcj** [comment]
I'm currently refactoring Oli Kestler's Kepler34 (Qt 5) code so that it will at least build in Linux.  I've also got mingw support in place (though it's been awhile since I've tried to build that), as I have zero desire to use Visual Studio or the Microsoft C++ compiler.  My current plan is to get the Qt 5 version basically working in Linux.  It will not have as many features as the gtkmm version for awhile, as there are a lot of new GUI features not in Kepler34.  Once I get the Qt 5 basics working, I will get the Windows build working.  I suspect it will take about a month to work through all the issues.  Ultimately I would like the Qt 5 version and the gtkmm-2 version on par with features, with the Qt 5 version sticking with a tabbed interface, and the gtkmm-2 version using the old-school multi-window interface.

**Comment by Gimmeapill** [comment]
OK, clear.
Thanks for the lightning fast feedback ;-)

BR,

LX

**Comment by ahlstromcj** [comment]
I am still working on getting the Qt 5 GUI to run properly on Linux.  Current issue is the recent-file list; works fine in the Gtkmm version, but can segfault in the Qt version.  Once I get the basics working, I will get the Windows version working, and then start making the Qt GUI have all the features the Gtkmm GUI has.

**Comment by Gimmeapill** [comment]
Cool stuff. I'll watch out the commits and spread the word once ready for testing (unfortunately I can't help much myself due to family things taking precedence, but at least I should be able to try the QT5 builds on Linux).

Cheers,

LX
