### ISSUE TITLE
Loop setting is ignored

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/sequencer64#32]
When I create a song in the song editor and then activate loop playing, the left and right marks are ignored.

(Sequencer64 0.9.18 2016-10-02 (Ubuntu 16.04 64bit))

**Comment by ahlstromcj** [comment]
For now, just make sure the "Song/Live" button is active in the main window.  If active, the
loop from L to R in perfedit will work.  The bug is that it should also work no matter what
that button says if you start playback from perfedit.  (perfedit = Song Editor).  Will fix real
soon, it's getting to be time for another bug-fix revision.

**Comment by ahlstromcj** [comment]
Actually, I have been testing with --enable-seq32jack, and the looping situation is worse without it.  I won't be able to fix it until this evening at the earliest.  If you're keen to experiment, add that enable flag to your configure call.    Sorry about that, there's a lot going on with the code right now.

**Comment by AndrewPy** [comment]
Thank you for your effort. It is not urgent. (I compiled and installed sequencer64 yesterday and discovered a few bugs that I wanted to report.)

**Comment by ahlstromcj** [comment]
Cool. Added some more fixes today. Thanks for helping!

**Comment by AndrewPy** [comment]
I have downloaded and installed 0.9.18.1 today and i have to say, now it is a fine piece of software. Thank you! 

I will test/use it in the next days/weeks and if I find a bug i will let you know.
