### ISSUE TITLE
Song cannot be edited any more after playing

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/sequencer64#33]
When i play a song in the song editor and then try to edit the song while it is playing and then stop the song, the song cannot be edited any more.

(Sequencer64 0.9.18 2016-10-02 (Ubuntu 16.04 64bit))

**Comment by ahlstromcj** [comment]
There's a bug in master where, if you click on an inactive (empty) track in Song Editor, it 
won't allow further editing.  Fixed in the latest fixups branch, so either grab that or a wait 
for me to get a chance to merge a number of bug fixes back into master.  Thanks for your 
patience!   The workaround is not click in empty track :-( and if you do, you have to restart
the app.
