### ISSUE TITLE
[feature request] recording live sessions

### ISSUE THREAD

**Issue by F0rth** [ahlstromcj/sequencer64#54]
First and foremost, thanks you very much for the sequencer64 user manuel, very well detailed and maintened. So, perhaps I overlooked it, otherwise a handy feature would be to be able to record live session to edit it later in song mode.

**Comment by ahlstromcj** [comment]
Thanks for the report!  I'm a bit tied up right now, working in the "rtmidi" branch.  I got PortMIDI working under Linux, and am now trying to reimplement the ALSA interface using a really warped version of RtMidi, and once that works, then add native JACK support.

Now, this feature looks like a good idea, but how should it work?  I assume you would like it to record MIDI events as normal, plus "record" the mutings and unmutings you do live, somehow, so that they either replace or add to the triggers shown in the Performance/Song Editor.  So, if you could sketch out the workflow you envision, that would help me think about it while I get the rtmidi branch working fully.  Thanks again!

**Comment by F0rth** [comment]
What I envisionned was a record button next to the play and stop buttons in the main window. In live mode, when the record button is armed it behaves as you said "replace or add to the triggers shown in the Performance/Song Editor".

**Comment by ahlstromcj** [comment]
This feature has been in placed for awhile now, so I will close this one.  If it still has issues, then you can open up a more specific issue.  Thanks!
